"use client";
import { useRouter } from "next/navigation";
import { useEffect, useRef, type RefObject } from "react";
import { isAgentId, type AgentId } from "@/lib/agents";
import type { SessionContext } from "@/lib/agent-protocol";
type Project = { id: string; name: string; path: string };
type Response = { agent: AgentId; taskId: number; projectId: string; projectPath: string; workitemId: number; prompt: string };
type Options = { taskIdRef: RefObject<string | null>; connected: boolean; isLoadingProjects: boolean; terminalReady: boolean; projects: Project[]; setAgent: (agent: AgentId) => void; setSelectedProjectId: (id: string) => void; setError: (message: string) => void; startSession: (agent: AgentId, project: Project, prompt: string, autoClose?: boolean, context?: SessionContext) => boolean; beginExecution: (execution: Required<SessionContext>) => void };
export function useTaskRun({ taskIdRef, connected, isLoadingProjects, terminalReady, projects, setAgent, setSelectedProjectId, setError, startSession, beginExecution }: Options) { const router = useRouter(); const started = useRef(false); useEffect(() => { const taskId = taskIdRef.current; if (!taskId || started.current || !connected || isLoadingProjects || !terminalReady) return; started.current = true; const controller = new AbortController(); void (async () => { try { const response = await fetch(`/api/tasks/${taskId}/execution-prompt`, { signal: controller.signal }); const body = await response.json() as Response | { error?: string }; if (!response.ok || !isAgentId((body as Response).agent) || typeof (body as Response).workitemId !== "number") throw new Error((body as { error?: string }).error ?? "Unable to prepare the task."); const result = body as Response; const project = projects.find((candidate) => candidate.id === result.projectId && candidate.path === result.projectPath); const execution: Required<SessionContext> = { projectId: result.projectId, workitemId: result.workitemId, taskId: result.taskId }; if (!project || !startSession(result.agent, project, result.prompt, false, execution)) throw new Error("The terminal connection is not ready."); setSelectedProjectId(project.id); setAgent(result.agent); beginExecution(execution); router.replace("/console"); } catch (error) { if (!controller.signal.aborted) setError(error instanceof Error ? error.message : "Unable to prepare the task."); } })(); return () => controller.abort(); }, [beginExecution, connected, isLoadingProjects, projects, router, setAgent, setError, setSelectedProjectId, startSession, taskIdRef, terminalReady]); }
